apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod_app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prod_app
    spec:
      containers:
      - name: prod_app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m