apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: image_name
        ports:
        - containerPort: 5000
        env:
          - name: HOST
            value: "$DB_HOST"
          - name: DBNAME
            value: "PRODDBNAME"
          - name: USER
            value: "$USER"
          - name: PASSWORD
            value: "$DBPASSWORD"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"