apiVersion: v1
kind: Service
metadata:
  name: prod-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: prod-app
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9090
  selector:
    app: prometheus-server