apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: gcr.io/project_id/image:tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
#---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: prod-app-autoscaler
#spec:
#  minReplicas: 1
#  maxReplicas: 10
#  scaleTargetRef:
#    apiVersion: extensions/v1beta1
#    kind: Deployment
#    name: prod-app-deployment
#  targetCPUUtilizationPercentage: 50
