apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prod-app-deployment
    spec:
      containers:
      - name: prod-app-deployment
        image: gcr.io/project_id/image:tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"