apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'stage-app-exporter'
        static_configs:
          - targets: ['35.195.235.170:80']
