apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stage-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stage-app
    spec:
      containers:
      - name: stage-app
        image: gcr.io/project_id/image:tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"