apiVersion: v1
kind: Service
metadata:
  name: stage-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: stage-app

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9090
      nodePort: 3000
  selector:
    app: prometheus-server
