name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE_WITH_TAG: gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA


jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the stack
#        run: docker-compose up -d
#      - name: Make tests with pytest
#        run: docker-compose exec -T app pytest -vv

  setup-build-publish:
#    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

       # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
       # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud --quiet auth configure-docker

       # Build the Docker image
      - name: Build Docker image
        run: |-
          docker build --tag "$IMAGE_WITH_TAG" .

        # Push the Docker image to Google Container Registry
      - name: Publish Docker image to GCR
        run: |-
          docker push "$IMAGE_WITH_TAG"

